language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - npm install

script:
  - npm test
  - npm run build
addons:
  chrome: stable
before_install:
  -  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: gh-pages
